server:
  port: 8082

spring:
  application:
    name: user-service
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password

logging:
  level:
    org.neo4j.driver: WARN
