server:
  port: 8083

spring:
  application:
    name: resume-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/resumedb

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging:
  level:
    org.springframework.data.mongodb: INFO
