server:
  port: 8083
  servlet:
    context-path: /resume

spring:
  application:
    name: resume-service
  data:
    mongodb:
      # THAY THẾ localhost:27017 bằng mongodbb:27017 (tên service DB trong Docker Compose)
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASS:root}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB_NAME:resume-service}?authSource=admin

# Cấu hình AI
openrouter:
  api-url: ${OPENROUTER_URL:https://openrouter.ai/api/v1/chat/completions}
  api-key: ${OPENROUTER_API_KEY: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}
  model: ${OPENROUTER_MODEL:x-ai/grok-4.1-fast-free} # Đã đổi thành biến môi trường

logging:
  level:
    root: INFO
    com.example.resume_service: DEBUG

app:
  services:
    # Resume gọi User Service, dùng biến môi trường
    profile: ${USER_SERVICE_URL:http://localhost:8082/profile}