server:
  port: 8083
  servlet:
    context-path: /resume

spring:
  application:
    name: resume-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/resume-service?authSource=admin

# Cấu hình OpenRouter
openrouter:
  api-url: https://openrouter.ai/api/v1/chat/completions
  # Key của bạn (đã điền sẵn)
  api-key: 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
  # Model miễn phí bạn chọn
  model: x-ai/grok-4.1-fast:free

logging:
  level:
    root: INFO
    com.example.resume_service: DEBUG

app:
  services:
    profile: http://localhost:8082/profile