server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  datasource:
    # THAY THẾ localhost:3307 bằng mysqldb:3306 (tên service DB trong Docker Compose)
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:identity_service}"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "85907b26b9b8c9608dc97840abdd8c32e749717b5f8771bd3da5bf68bcfce06b"
  valid-duration: 3600 # giây
  refreshable-duration: 36000 # giây

app:
  services:
    # Identity gọi User Service, dùng biến môi trường
    profile: ${USER_SERVICE_URL:http://localhost:8082/profile}