server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "85907b26b9b8c9608dc97840abdd8c32e749717b5f8771bd3da5bf68bcfce06b"
  valid-duration: 3600 # giây
  refreshable-duration: 36000 # giây

app:
  services:
    profile: http://localhost:8082/profile