server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8081
          predicates:
            - Path=/identity/**
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/profile/users/**
        - id: resume_service
          uri: http://localhost:8083
          predicates:
            - Path=/resume/api/cvs/**
        - id: notification_service
          uri: http://localhost:8084
          predicates:
            - Path=/notification/**
        - id: payment_service
          uri: http://localhost:8080
          predicates:
            - Path=/api/payments/**