server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Sử dụng biến môi trường. Giá trị mặc định là localhost (cho chạy local)
        - id: identity_service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/identity/**
        - id: user_service
          uri: ${USER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/profile/users/**
        - id: resume_service
          uri: ${RESUME_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/resume/api/cvs/**
        - id: notification_service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/notification/**
        - id: payment_service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/payments/**
app:
  identity-service-url: ${IDENTITY_SERVICE_URL:http://localhost:8081}
